### ISSUE TITLE
No variable list?

### ISSUE THREAD

**Issue by NikNikovsky** [thetechxplore/SystemdBot#2]
Hey mate,
Could you make an index with the variables for the user, server, etc.?
Would be appreciated

**Comment by thetechxplore** [comment]
Yes, this will be something added in the next update

**Comment by NikNikovsky** [comment]
Welp, i am hoping to see something like on Dyno's or MEE6's dashboard

Regards,
Nik Nikovsky
------------------------------------------------
Life haver
Not flexing nitro
Computer Clan Supporter
Tries to have a YouTube channel
Touches grass every day
Has a GitHub repository for windows xp, because yes.
They will have to glue you back. In hell!
________________________________

**Comment by NikNikovsky** [comment]
> Yes, this will be something added in the next update

You forgot about this, didn't you?

**Comment by thetechxplore** [comment]
Hey so it's not needed...I technically did something like that, but it's in a database
